"""Score-level utilities ported from ``svend4/meta2/puzzle_reconstruction/scoring``.

This subpackage complements ``triage4.matching``: where matching handles
pairwise distances and fusion, scoring handles thresholding, evidence
aggregation, rank-list fusion and global ranking across a whole batch of
scored entities.
"""

from .evidence_aggregator import (
    EvidenceConfig,
    EvidenceScore,
    aggregate_evidence,
    batch_aggregate,
    compute_confidence,
    rank_by_evidence,
    threshold_evidence,
    weight_evidence,
)
from .pair_ranker import (
    RankConfig,
    RankResult,
    RankedPair,
    build_rank_matrix,
    compute_pair_score,
    merge_rank_results,
)
from .pair_ranker import rank_pairs as rank_pairs_detailed
from .pair_filter import (
    CandidatePair as FilterCandidatePair,
    FilterConfig,
    FilterReport,
    batch_filter,
    filter_by_inlier_count,
    filter_pairs,
    filter_top_k,
    filter_top_k_per_fragment,
    merge_filter_results,
)
from .pair_filter import deduplicate_pairs as dedup_filter_pairs
from .pair_filter import filter_by_score as filter_by_score_threshold
from .global_ranker import (
    RankedPair as GlobalRankedPair,
    RankingConfig,
    aggregate_score_matrices,
    batch_global_rank,
    global_rank,
    normalize_matrix,
    score_vector,
    top_k_candidates,
)
from .global_ranker import rank_pairs as global_rank_pairs
from .match_evaluator import (
    EvalConfig,
    EvalReport,
    MatchEval,
    aggregate_eval,
    compute_f_score,
    compute_precision,
    compute_recall,
    evaluate_batch_matches,
    evaluate_match,
    rank_matches,
)
from .match_evaluator import filter_by_score as filter_eval_by_score
from .consistency_checker import (
    ConsistencyIssue,
    ConsistencyReport,
    batch_consistency_check,
    check_all_present,
    check_canvas_bounds,
    check_gap_uniformity,
    check_score_threshold,
    check_unique_ids,
    run_consistency_check,
)
from .rank_fusion import (
    borda_count,
    fuse_rankings,
    normalize_scores,
    reciprocal_rank_fusion,
    score_fusion,
)
from .threshold_selector import (
    ThresholdConfig,
    ThresholdResult,
    apply_threshold,
    batch_select_thresholds,
    select_adaptive_threshold,
    select_f1_threshold,
    select_fixed_threshold,
    select_otsu_threshold,
    select_percentile_threshold,
    select_threshold,
)

__all__ = [
    "ConsistencyIssue",
    "ConsistencyReport",
    "EvalConfig",
    "EvalReport",
    "EvidenceConfig",
    "EvidenceScore",
    "FilterCandidatePair",
    "FilterConfig",
    "FilterReport",
    "GlobalRankedPair",
    "MatchEval",
    "RankConfig",
    "RankingConfig",
    "RankResult",
    "RankedPair",
    "ThresholdConfig",
    "ThresholdResult",
    "aggregate_eval",
    "aggregate_evidence",
    "aggregate_score_matrices",
    "apply_threshold",
    "batch_aggregate",
    "batch_consistency_check",
    "batch_filter",
    "batch_global_rank",
    "batch_select_thresholds",
    "borda_count",
    "build_rank_matrix",
    "check_all_present",
    "check_canvas_bounds",
    "check_gap_uniformity",
    "check_score_threshold",
    "check_unique_ids",
    "compute_confidence",
    "compute_f_score",
    "compute_pair_score",
    "compute_precision",
    "compute_recall",
    "dedup_filter_pairs",
    "evaluate_batch_matches",
    "evaluate_match",
    "filter_by_inlier_count",
    "filter_by_score_threshold",
    "filter_eval_by_score",
    "filter_pairs",
    "filter_top_k",
    "filter_top_k_per_fragment",
    "fuse_rankings",
    "global_rank",
    "global_rank_pairs",
    "merge_filter_results",
    "merge_rank_results",
    "normalize_matrix",
    "normalize_scores",
    "rank_by_evidence",
    "rank_matches",
    "rank_pairs_detailed",
    "reciprocal_rank_fusion",
    "run_consistency_check",
    "score_fusion",
    "score_vector",
    "select_adaptive_threshold",
    "select_f1_threshold",
    "select_fixed_threshold",
    "select_otsu_threshold",
    "select_percentile_threshold",
    "select_threshold",
    "threshold_evidence",
    "top_k_candidates",
    "weight_evidence",
]
